### ISSUE TITLE
🚧 TODOs

### ISSUE THREAD

**Issue by KATT** [KATT/shop#2]
**Yes** - I know I am going crazy on the emojis. It makes things less serious and more fun.

- [x] 🎉 Boilerplate, project setup
- [x] 😻 gitignore `*.js`
- [x] 🚀 now.sh deployment setup
- [x] 🚀 local prisma cluster
- [x] 🏦 Basic data modelling
- [x] 🚨 linting
- [x] 🛍 Basic checkout component with SSR
- [x] ✅ Basic E2E
- [x] 💚 Circle CI bootstrap
- [x] 🛒 Create cart on page load `getInitialProps`
  - [x] Naive create cart every time
  - [x] Client: get cartId from cookie
  - [x] Client: cart from apollo cache if already fetched
  - [x] Server: get cart id + write to cookie - requires custom serving of app
- [x] 🛒 Add product to cart
  - [x] `AddToCartMutation`
  - [x] If product already in cart, up qty
- [x] 🔢 Update quantity +1 / -1 `<button />`
  - [x] 📈 API Support
  - [x] 🔥 Delete row if reaches 0
  - [x] 🐎 Optimistic updates
  - [x] 😮 NoJS support
- [x] 🔢 Update quantity `<input />`
  - [x] 🔥 Delete row if set to 0
  - [x] 🐎 Optimistic updates
  - [x] 😮 NoJS support
- [x] 🔥 Delete row `<button />`
- [x] 💬 Modal open
- [ ] ♿️ Accessibility, semantic code
- [ ] 💄Design 🙀 
- [x] 🔍 Headers, meta data
- [ ] 🔍 Microdata
- [x] 💰 Support for discounts
- [x] ✅ Happy-path E2E - add product to cart, go checkout, up/down qty
- [x] 📚 Document
  - [x] Setup
  - [x] Brief explain prisma, local cluster etc
  - [x] E2E (selenium reqs, run with nojs, etc)
  - [x] Features (server-render, etc)
  - [ ] Look through code, add **_🚧TODOs_**
- [x] 💚 CI 
  - [x] 🎉 Bootstrap Circle CI
  - [ ] ~🐛 Fix why it fails [_( ⬛️ awaiting response from prisma guys)_](https://github.com/graphcool/prisma/issues/2000)~
  - [x] 💚 Travis!
  - [x] ✅ Run `web`/`api` tests
  - [x] ✅ E2E run #8 
  - [ ] 🤔 % Coverage?
  - [x] 🥇 Badges in README
- [ ] 🔒 prod environment
- [ ] 🖖 Test + continuous deployment on merge to master 
- [ ] 🐎 Optimise performance [for Europe](https://www.graph.cool/forum/t/prisma-cloud-node-app-hosting-for-speed-low-latency/2774)
- [ ] 🎨 Improve monorepo setup. Share deps, easy setup, running, etc.
- [x] 🚨 improve linting / autofixing, not quite satisfied (#7 - will be updated incrementally as we edit files)
- [ ] 👯‍♂️ Share code between api/web better
- [ ] 🎨 Make it easier to write the mutation render prop components with nojs fallback
- [x] 🐎 Cache CI deps etc #9
- [ ] 🐎 Travis cache prisma/mysql cluster #10 
- [x] 🗣 Brag on Twitter

**Comment by KATT** [comment]
Everything moved into [separate issues](./)
